### ISSUE TITLE
Code fails without a GPU

### ISSUE THREAD

**Issue by benob** [yusuketomoto/chainer-char-rnn#1]
When running without a GPU, the code still calls cuda functions:

```
python2 train.py --gpu -1
data/tinyshakespeare/input.txt
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    cur_log_perp = cuda.zeros(())
  File "/home/favre/.local/lib/python2.7/site-packages/chainer/cuda.py", line 523, in zeros
    return full(shape, 0, dtype, stream=stream)
  File "/home/favre/.local/lib/python2.7/site-packages/chainer/cuda.py", line 512, in full
    array = empty(shape, dtype)
  File "/home/favre/.local/lib/python2.7/site-packages/chainer/cuda.py", line 495, in empty
    return gpuarray.empty(shape, dtype, allocator=mem_alloc)
NameError: global name 'gpuarray' is not defined
```

**Comment by yusuketomoto** [comment]
Thank you for your report. I fixed it.
